-- Departments table for AttendIQ.
-- Use uuid values generated by the backend or by a database UUID function.

create table if not exists departments (
  id uuid primary key,
  name text not null,
  code text not null unique,
  description text,
  created_at timestamptz not null default now()
);

-- Subjects table
create table if not exists subjects (
  id uuid primary key,
  name text not null,
  code text not null unique,
  faculty_id uuid references profiles(id) on delete set null,
  department_id uuid references departments(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Subject enrollments (many-to-many)
create table if not exists subject_enrollments (
  id uuid primary key,
  subject_id uuid not null references subjects(id) on delete cascade,
  student_id uuid not null references profiles(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  unique (subject_id, student_id)
);

-- Attendance sessions & records
create table if not exists attendance_sessions (
  id uuid primary key,
  subject_id uuid not null references subjects(id) on delete cascade,
  faculty_id uuid references profiles(id) on delete set null,
  session_name text,
  start_time timestamptz,
  end_time timestamptz,
  status text default 'created',
  created_at timestamptz not null default now()
);

create table if not exists attendance_records (
  id uuid primary key,
  session_id uuid not null references attendance_sessions(id) on delete cascade,
  student_id uuid not null references profiles(id) on delete cascade,
  attendance_status text not null,
  marked_at timestamptz not null default now(),
  unique(session_id, student_id)
);
